#!/usr/bin/env bash
# Add multiple tags to an image with Docker Hub automated builds
# Credit to Nigel Brown
# https://windsock.io/automated-docker-image-builds-with-multiple-tags/

set -e

echo "Checking for additional tags related to $SOURCE_BRANCH"

push_tags () {
    echo "Tagging ${tag} from ${IMAGE_NAME}"
    docker tag ${DOCKER_REPO}:${base_tag} ${DOCKER_REPO}:${tag}
    docker push ${DOCKER_REPO}:${tag}
}

# Tag and push image for each additional tag
case $SOURCE_BRANCH in
    "1.1.1")
        base_tag="1.1.1"
        tags=( "1.1.1-alpine" "1.1.1-stable" "stable" "lts" "latest" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        base_tag="1.1.1-lite"
        tags=( "lite" "stable-lite" "lts-lite" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        base_tag="1.1.1-distroless"
        tags=( "distroless" "stable-distroless" "lts-distroless" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        base_tag="1.1.1-dev"
        tags=( "dev" "stable-dev" "lts-dev" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    "1.1.0")
        base_tag="1.1.0"
        tags=( "1.1.0-alpine" "1.1.0-stable" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    "1.0.2")
        base_tag="1.0.2"
        tags=( "1.0.2-alpine" "1.0.2-stable" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    "1.1.1c")
        base_tag="1.1.1c"
        tags=( "1.1.1c-alpine" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    "1.1.0k")
        base_tag="1.1.0k"
        tags=( "1.1.0k-alpine" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    "1.0.2s")
        base_tag="1.0.2s"
        tags=( "1.0.2s-alpine" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    *)
        :
        ;;
esac
